# Stage 1: Build the Angular app
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli

COPY . .

EXPOSE 4200
ENTRYPOINT ["tail", "-f", "/dev/null"]
# CMD ["ng", "serve"]