# Stage 1: Build the Angular app
FROM ubuntu/node:18.19.1-24.04_edge

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli

COPY . .

EXPOSE 4200
ENTRYPOINT ["tail", "-f", "/dev/null"]
# CMD ["ng", "serve"]